vocab_fr=[
"où:where",
"quand:when",
"comment:how",
"pourquoi:why",
"combien de:how much, how many",
"parce que:because",
"ouverte:open",
"un chien:a dog",
"un meuble:a piece of furniture",
"un réveil:an alarm clock",
"une casquette:a cap",
"à louer:for rent",
"besoin:need",
"devinir:guess",
"particulièrement:particularly",
"la carte:the map",
"bien sur!:of course!",
"proposés:proposed",
"je vous propose:i propose",
"nous mangeons:we eat",
"finir:to finish",
"nous finissons:we finish",
"vous finissez:you all finish",
"je finis:i finish",
"il finit:it ends",
"souvent:often",
"agir:to act",
"réfléchir à:to reflect upon",
"réussir:to succeed",
"bientôt:soon",
]
